# Generated by Django 3.1.7 on 2022-01-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquequestion',
            name='question_text',
            field=models.TextField(),
        ),
    ]
