# Generated by Django 3.1.7 on 2022-01-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0003_bqanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BqAnswer',
        ),
    ]
