# Generated by Django 3.1.7 on 2022-01-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0004_delete_bqanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BqAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_fraction', models.CharField(max_length=100)),
                ('answer_text', models.TextField()),
                ('quesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcm.banquequestion')),
            ],
        ),
    ]
