# Generated by Django 3.1.7 on 2022-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0005_bqanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(default='---', max_length=150)),
            ],
        ),
    ]
