# Generated by Django 3.1.7 on 2022-01-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0006_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2')], max_length=100),
        ),
    ]
