# Generated by Django 3.1.7 on 2022-01-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0007_auto_20220117_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.CharField(choices=[], default='1ER', max_length=100),
        ),
    ]
