# Generated by Django 3.1.7 on 2022-01-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0008_auto_20220117_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='matiere',
            field=models.CharField(choices=[], default='CHIMIE', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.CharField(choices=[('1ER', '1ER'), ('2EM', '2EM')], default='1ER', max_length=100),
        ),
    ]
