# Generated by Django 3.1.7 on 2022-01-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0009_auto_20220117_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='matiere',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.TextField(),
        ),
    ]
