# Generated by Django 3.1.7 on 2022-01-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0010_auto_20220117_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed', models.TextField()),
                ('success', models.TextField()),
            ],
        ),
    ]
