# Generated by Django 3.1.7 on 2021-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0030_alter_answerpaper_user_ip_max_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment',
            field=models.CharField(choices=[('default', 'Enroll Request'), ('open', 'Open Enrollment')], max_length=32, verbose_name='enrollment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='instructions'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='view_grade',
            field=models.BooleanField(default=False, verbose_name='view grade'),
        ),
    ]
