# Generated by Django 3.1.7 on 2021-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', 'default_grading_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsystem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Grading System'),
        ),
    ]
